/**
 * MarketOS prototype — seed data.
 *
 * Mock-only. Never import from this file in non-prototype code.
 */
import {
  BidStatus,
  Category,
  type Bid,
  type Mission,
  MissionStatus,
  type Notification,
  NotificationType,
  type OrgSettings,
  type Person,
  type Pool,
  Tier,
} from '@/lib/prototypes/market-os/types';

export const CURRENT_USER: Person = {
  id: 'u-alex',
  name: 'Alex Morgan',
  role: 'Product Lead',
  reputation: 847,
  tier: Tier.Gold,
  completed: 14,
  onTime: 93,
  rating: 4.7,
  totalEarned: 84200,
  skills: [
    'Figma',
    'User Research',
    'Prototyping',
    'Design Systems',
    'UX Writing',
    'Usability Testing',
    'Strategy',
  ],
  specialty: Category.Design,
};

export const PEOPLE: Person[] = [
  CURRENT_USER,
  {
    id: 'u-jamie',
    name: 'Jamie L.',
    role: 'Senior Engineer',
    reputation: 910,
    tier: Tier.Platinum,
    completed: 22,
    onTime: 96,
    rating: 4.9,
    totalEarned: 138400,
    skills: ['TypeScript', 'Postgres', 'AWS', 'Performance', 'API design'],
    specialty: Category.Engineering,
  },
  {
    id: 'u-priya',
    name: 'Priya S.',
    role: 'Researcher',
    reputation: 782,
    tier: Tier.Gold,
    completed: 11,
    onTime: 91,
    rating: 4.6,
    totalEarned: 52400,
    skills: ['Discovery', 'Customer interviews', 'Synthesis', 'Survey design'],
    specialty: Category.Research,
  },
  {
    id: 'u-chris',
    name: 'Chris O.',
    role: 'Marketing Lead',
    reputation: 855,
    tier: Tier.Gold,
    completed: 17,
    onTime: 88,
    rating: 4.5,
    totalEarned: 71600,
    skills: ['Email', 'Brand', 'Copy', 'Lifecycle', 'Paid social'],
    specialty: Category.Marketing,
  },
  {
    id: 'u-sarah',
    name: 'Sarah K.',
    role: 'Design Director',
    reputation: 920,
    tier: Tier.Platinum,
    completed: 26,
    onTime: 95,
    rating: 4.8,
    totalEarned: 162900,
    skills: ['Vision', 'Mentoring', 'Service design', 'Workshops'],
    specialty: Category.Design,
  },
  {
    id: 'u-tom',
    name: 'Tom R.',
    role: 'Strategy Analyst',
    reputation: 690,
    tier: Tier.Silver,
    completed: 9,
    onTime: 89,
    rating: 4.4,
    totalEarned: 38600,
    skills: ['Market sizing', 'Excel', 'Investor decks'],
    specialty: Category.Research,
  },
  {
    id: 'u-dev',
    name: 'Dev Patel',
    role: 'Backend Engineer',
    reputation: 740,
    tier: Tier.Silver,
    completed: 12,
    onTime: 92,
    rating: 4.5,
    totalEarned: 64200,
    skills: ['Node', 'PostgreSQL', 'Caching', 'Observability'],
    specialty: Category.Engineering,
  },
  {
    id: 'u-mira',
    name: 'Mira T.',
    role: 'People Ops',
    reputation: 615,
    tier: Tier.Silver,
    completed: 8,
    onTime: 100,
    rating: 4.7,
    totalEarned: 22400,
    skills: ['Policy', 'Onboarding', 'Comp design', 'Notion'],
    specialty: Category.HR,
  },
  {
    id: 'u-yuki',
    name: 'Yuki N.',
    role: 'Operations',
    reputation: 580,
    tier: Tier.Bronze,
    completed: 6,
    onTime: 86,
    rating: 4.3,
    totalEarned: 18900,
    skills: ['Process', 'Vendor management', 'Logistics'],
    specialty: Category.Operations,
  },
];

export const MISSIONS: Mission[] = [
  {
    id: 'm-001',
    title: 'Redesign onboarding flow',
    cat: Category.Design,
    budget: 8400,
    deadline: '2026-05-15',
    status: MissionStatus.Open,
    bids: 2,
    posted: '3 days ago',
    desc: 'Redesign the end-to-end onboarding experience for new users. The current flow has a 40% drop-off at step 3. We need a tested, ship-ready design with Figma handoff.',
    deliverables: [
      'User research summary (3 existing user interviews)',
      'Wireframes for all 6 onboarding steps',
      'High-fidelity Figma prototype',
      'Handoff doc with design tokens and specs',
    ],
    poster: 'Sarah K.',
    posterId: 'u-sarah',
  },
  {
    id: 'm-002',
    title: 'Q2 competitive analysis',
    cat: Category.Research,
    budget: 3200,
    deadline: '2026-05-08',
    status: MissionStatus.Open,
    bids: 1,
    posted: '1 day ago',
    desc: 'Document the feature set, pricing, and positioning of our top 5 competitors. Identify gaps we can exploit in H2.',
    deliverables: [
      'Competitor matrix (features, pricing, ICP)',
      '3–5 page analysis doc',
      'Recommendations for positioning',
    ],
    poster: 'Tom R.',
    posterId: 'u-tom',
  },
  {
    id: 'm-003',
    title: 'Launch email campaign — Series A',
    cat: Category.Marketing,
    budget: 5600,
    deadline: '2026-05-20',
    status: MissionStatus.Active,
    bids: 1,
    posted: '5 days ago',
    desc: 'Write and build a 4-email drip campaign announcing our Series A. Covers investor intro, product traction, team growth, and future roadmap.',
    deliverables: [
      '4 email copydecks',
      'HTML templates (mobile-optimised)',
      'Send schedule and A/B test plan',
    ],
    poster: 'Chris O.',
    posterId: 'u-chris',
  },
  {
    id: 'm-004',
    title: 'Backend API performance audit',
    cat: Category.Engineering,
    budget: 6800,
    deadline: '2026-05-10',
    status: MissionStatus.Open,
    bids: 4,
    posted: '2 days ago',
    desc: 'Audit our REST API for performance bottlenecks. Median response time is 340ms; target is under 120ms. Deliver a prioritised fix list.',
    deliverables: [
      'Performance benchmark report',
      'Top 10 bottlenecks ranked by impact',
      'Pull requests for quick wins (< 4h each)',
    ],
    poster: 'Dev Patel',
    posterId: 'u-dev',
  },
  {
    id: 'm-005',
    title: 'Employee handbook update',
    cat: Category.HR,
    budget: 2400,
    deadline: '2026-05-25',
    status: MissionStatus.Open,
    bids: 0,
    posted: 'Today',
    desc: 'Update the company handbook to reflect our MarketOS operating model, new mission-based compensation structure, and remote-first policies.',
    deliverables: [
      'Revised handbook doc (Notion format)',
      'Change summary for all-hands presentation',
    ],
    poster: 'Mira T.',
    posterId: 'u-mira',
  },
  {
    id: 'm-006',
    title: 'Market sizing — DACH region',
    cat: Category.Research,
    budget: 3600,
    deadline: '2026-06-01',
    status: MissionStatus.Open,
    bids: 1,
    posted: '4 days ago',
    desc: 'Size the addressable market for MarketOS in Germany, Austria, and Switzerland. Use bottom-up and top-down methodology.',
    deliverables: [
      'TAM/SAM/SOM breakdown',
      'Methodology doc',
      '2-page exec summary',
    ],
    poster: 'Tom R.',
    posterId: 'u-tom',
  },
  {
    id: 'm-007',
    title: 'Sales deck refresh',
    cat: Category.Design,
    budget: 4000,
    deadline: '2026-04-30',
    status: MissionStatus.Active,
    bids: 1,
    posted: '8 days ago',
    desc: 'Refresh the sales deck to reflect new positioning, Series A messaging, and updated product screenshots.',
    deliverables: [
      'Updated deck (Slides/PPT)',
      'Slide-by-slide speaker notes',
      '2 design variants',
    ],
    poster: 'Chris O.',
    posterId: 'u-chris',
  },
  {
    id: 'm-008',
    title: 'Infrastructure cost review',
    cat: Category.Engineering,
    budget: 5200,
    deadline: '2026-05-30',
    status: MissionStatus.Open,
    bids: 1,
    posted: '6 days ago',
    desc: 'Audit our AWS spend and identify 20%+ cost reduction opportunities without performance regression.',
    deliverables: [
      'Cost breakdown by service',
      'Prioritised reduction roadmap',
      'Estimated savings per action',
    ],
    poster: 'Yuki N.',
    posterId: 'u-yuki',
  },
];

export const BIDS_BY_MISSION: Record<string, Bid[]> = {
  'm-001': [
    {
      id: 'b-001',
      missionId: 'm-001',
      bidderId: 'u-jamie',
      bidderName: 'Jamie L.',
      amount: 7700,
      status: BidStatus.Pending,
      daysAgo: 1,
      proposal:
        'Strong fit — I shipped the v3 onboarding redesign at Vox & Tech that lifted activation by 22%.',
      reputation: 910,
    },
    {
      id: 'b-002',
      missionId: 'm-001',
      bidderId: 'u-priya',
      bidderName: 'Priya S.',
      amount: 8200,
      status: BidStatus.Pending,
      daysAgo: 2,
      proposal:
        'I can run the user research and pair with a designer in my network for the visuals.',
      reputation: 782,
    },
  ],
  'm-002': [
    {
      id: 'b-003',
      missionId: 'm-002',
      bidderId: 'u-tom',
      bidderName: 'Tom R.',
      amount: 3000,
      status: BidStatus.Pending,
      daysAgo: 0,
      proposal:
        "I've done two of these for adjacent SaaS markets. Can deliver in 5 days.",
      reputation: 690,
    },
  ],
  'm-003': [
    {
      id: 'b-004',
      missionId: 'm-003',
      bidderId: 'u-chris',
      bidderName: 'Chris O.',
      amount: 5400,
      status: BidStatus.Accepted,
      daysAgo: 4,
      proposal:
        'Series A copy is my zone — I led the campaign for two of our portfolio companies.',
      reputation: 855,
    },
  ],
  'm-004': [
    {
      id: 'b-005',
      missionId: 'm-004',
      bidderId: 'u-jamie',
      bidderName: 'Jamie L.',
      amount: 6300,
      status: BidStatus.Shortlisted,
      daysAgo: 1,
      proposal: 'Postgres + Node specialist. I can find the wins in 48h.',
      reputation: 910,
    },
    {
      id: 'b-006',
      missionId: 'm-004',
      bidderId: 'u-dev',
      bidderName: 'Dev Patel',
      amount: 6500,
      status: BidStatus.Pending,
      daysAgo: 1,
      proposal: "I'm already familiar with this codebase from a prior mission.",
      reputation: 740,
    },
    {
      id: 'b-007',
      missionId: 'm-004',
      bidderId: 'u-alex',
      bidderName: 'Alex Morgan',
      amount: 6200,
      status: BidStatus.Pending,
      daysAgo: 2,
      proposal:
        'Cross-disciplinary — happy to translate the engineering output into a leadership-friendly story.',
      reputation: 847,
    },
    {
      id: 'b-008',
      missionId: 'm-004',
      bidderId: 'u-yuki',
      bidderName: 'Yuki N.',
      amount: 6800,
      status: BidStatus.Pending,
      daysAgo: 3,
      proposal: 'Can pair with engineering and own the cost side.',
      reputation: 580,
    },
  ],
  'm-006': [
    {
      id: 'b-009',
      missionId: 'm-006',
      bidderId: 'u-alex',
      bidderName: 'Alex Morgan',
      amount: 3400,
      status: BidStatus.Shortlisted,
      daysAgo: 5,
      proposal: 'I have a working DACH dataset I can lean on.',
      reputation: 847,
    },
  ],
};

export const POOL: Pool = {
  period: 'Q2 2026',
  ratio: 42,
  total: 248_000,
  missions: 142_000,
  base: 80_000,
  unallocated: 26_000,
  history: [
    { period: 'Q1 2025', total: 168_000 },
    { period: 'Q2 2025', total: 184_000 },
    { period: 'Q3 2025', total: 196_000 },
    { period: 'Q4 2025', total: 218_000 },
    { period: 'Q1 2026', total: 232_000 },
    { period: 'Q2 2026', total: 248_000 },
  ],
  payouts: [
    {
      person: 'Chris O.',
      mission: 'Launch email campaign — Series A',
      amount: 5400,
      releaseDate: '2026-05-22',
    },
    {
      person: 'Jamie L.',
      mission: 'Backend API audit',
      amount: 6300,
      releaseDate: '2026-05-12',
    },
    {
      person: 'Sarah K.',
      mission: 'Sales deck refresh',
      amount: 4000,
      releaseDate: '2026-05-02',
    },
  ],
};

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'n-1',
    type: NotificationType.BidShortlisted,
    title: 'Your bid was shortlisted',
    body: 'You\'re shortlisted on "Market sizing — DACH region" ($3,400).',
    ts: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    read: false,
    link: '/prototypes/market-os/app/missions/m-006',
  },
  {
    id: 'n-2',
    type: NotificationType.BidReceived,
    title: 'New bid on your mission',
    body: 'Jamie L. bid $7,700 on "Redesign onboarding flow".',
    ts: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    read: false,
    link: '/prototypes/market-os/app/missions/m-001',
  },
  {
    id: 'n-3',
    type: NotificationType.MissionPosted,
    title: 'New mission you might like',
    body: '"Backend API performance audit" — $6,800 — closes May 10.',
    ts: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    read: false,
    link: '/prototypes/market-os/app/missions/m-004',
  },
  {
    id: 'n-4',
    type: NotificationType.ReputationUp,
    title: 'Reputation +18',
    body: 'Your "Mobile app redesign — v3" delivery earned a 5.0 review.',
    ts: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    read: true,
    link: '/prototypes/market-os/app/profile',
  },
  {
    id: 'n-5',
    type: NotificationType.PoolUpdate,
    title: 'Q2 pool grew by $14k',
    body: 'Latest revenue cycle pushed the unallocated portion to $26k.',
    ts: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    read: true,
    link: '/prototypes/market-os/app/pool',
  },
  {
    id: 'n-6',
    type: NotificationType.MissionCompleted,
    title: 'Mission completed',
    body: 'Sales deck refresh has been marked completed by Chris O.',
    ts: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    read: true,
    link: '/prototypes/market-os/app/missions/m-007',
  },
];

export const ORG_SETTINGS_DEFAULT: OrgSettings = {
  name: 'Captico Ltd.',
  memberCount: 86,
  ratio: 42,
  baseSplit: 32,
  period: 'quarter',
  accent: 'orange',
  dark: false,
};

export const MISSION_HISTORY = [
  {
    title: 'Design system overhaul',
    cat: Category.Design,
    earned: 9200,
    rating: 4.9,
    completed: 'Mar 2026',
  },
  {
    title: 'Sales pipeline analysis',
    cat: Category.Research,
    earned: 4100,
    rating: 4.6,
    completed: 'Feb 2026',
  },
  {
    title: 'Mobile app redesign — v3',
    cat: Category.Design,
    earned: 11400,
    rating: 5.0,
    completed: 'Feb 2026',
  },
  {
    title: 'Customer interview synthesis',
    cat: Category.Research,
    earned: 3200,
    rating: 4.7,
    completed: 'Jan 2026',
  },
  {
    title: 'Q4 marketing strategy',
    cat: Category.Marketing,
    earned: 5600,
    rating: 4.5,
    completed: 'Dec 2025',
  },
];

export function getMission(id: string): Mission | undefined {
  return MISSIONS.find((m) => m.id === id);
}

export function getBids(missionId: string): Bid[] {
  return BIDS_BY_MISSION[missionId] ?? [];
}

export function getMyBids(): Bid[] {
  return Object.values(BIDS_BY_MISSION)
    .flat()
    .filter((b) => b.bidderId === CURRENT_USER.id);
}
